#!/bin/bash
#"crontab -e" line:
#30 12,16,20 * * 1-5 $HOME/bin/rsync_home.sh
BACKHOST=$1
/usr/bin/rsync -CAavz $HOME $USER@$BACKHOST:$HOME/backup > $HOME/projects/rsync_backup/log_$(date --iso-8601=minutes).txt 2>&1
#rsync -Cavz --delete ...
#rsync -aAv --backup --backup-dir=${DATA}_backups/$(date +%y%m%d) ...
#rsync --progress --include='*.bam*' --include='*/' --exclude='*' -LaAv $(pwd) ...
